"""modified actvation history model id


Revision ID: 0843a32081ed
Revises: bcf542f94fa5
Create Date: 2025-02-16 15:27:20.305243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0843a32081ed'
down_revision: Union[str, None] = 'bcf542f94fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activation_history', 'transaction_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activation_history', 'transaction_id',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
