"""modified user model


Revision ID: 2a77fc1d4e53
Revises: 0843a32081ed
Create Date: 2025-02-16 15:30:18.456088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a77fc1d4e53'
down_revision: Union[str, None] = '0843a32081ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_kyc_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_kyc_verified')
    # ### end Alembic commands ###
