"""added reward points in community model

Revision ID: 302c97ed32cd
Revises: a08df08aa956
Create Date: 2025-02-16 10:05:32.879153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302c97ed32cd'
down_revision: Union[str, None] = 'a08df08aa956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('reward_points', sa.DECIMAL(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community', 'reward_points')
    # ### end Alembic commands ###
