"""initial migration

Revision ID: 4264b7b2363a
Revises: 
Create Date: 2025-01-21 11:02:39.910295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4264b7b2363a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant_referrals', 'referred_by',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.create_foreign_key(None, 'merchant_referrals', 'users', ['referred_by'], ['referral_id'], onupdate='cascade', ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'merchant_referrals', type_='foreignkey')
    op.alter_column('merchant_referrals', 'referred_by',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
