"""modified merchant referral model

Revision ID: 4c0ec4ef2eaf
Revises: 4264b7b2363a
Create Date: 2025-01-21 14:32:37.654118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4c0ec4ef2eaf'
down_revision: Union[str, None] = '4264b7b2363a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant_details', 'contact_number',
               existing_type=mysql.VARCHAR(length=13),
               nullable=False)
    op.alter_column('merchant_details', 'business_email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant_details', 'business_email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('merchant_details', 'contact_number',
               existing_type=mysql.VARCHAR(length=13),
               nullable=True)
    # ### end Alembic commands ###
