"""added admin accounts model

Revision ID: 6cbb153afaac
Revises: 
Create Date: 2025-02-06 13:15:06.781087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbb153afaac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_accounts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=10), nullable=False),
    sa.Column('account_type', sa.Enum('SUPERADMIN', 'ADMIN', 'CUSTOMER_SUPPORT'), server_default=sa.text("'CUSTOMER_SUPPORT'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['mobile_number'], ['users.mobile_number'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_admin_accounts_user_id'), 'admin_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_accounts_user_id'), table_name='admin_accounts')
    op.drop_table('admin_accounts')
    # ### end Alembic commands ###
