"""added activation history model:



Revision ID: bcf542f94fa5
Revises: 302c97ed32cd
Create Date: 2025-02-16 14:58:08.141859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf542f94fa5'
down_revision: Union[str, None] = '302c97ed32cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activation_history',
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('activated_by', sa.String(length=36), nullable=False),
    sa.Column('receiver_id', sa.String(length=36), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('receiver_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('activated_in', sa.Enum('mobile', 'web'), server_default='mobile', nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded'), server_default='pending', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_activation_history_reference_id'), 'activation_history', ['reference_id'], unique=False)
    op.create_index(op.f('ix_activation_history_transaction_id'), 'activation_history', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activation_history_transaction_id'), table_name='activation_history')
    op.drop_index(op.f('ix_activation_history_reference_id'), table_name='activation_history')
    op.drop_table('activation_history')
    # ### end Alembic commands ###
